---
title: Using Blogdown
author: Aaron Gullickson
date: '2022-05-29'
categories:
  - blogdown
  - R
  - help
slug: using-blogdown
---

This is a blogdown site created from the skeleton template with a few adjustments and additions (including this page).

## Creating New Posts

Once you have your `blogdown` site set up, you can add new posts in one of two ways:

1. You can use the Addin menu to go to `BLOGDOWN > New Post` and fill in the information from the dialog. 
2. You can use the `blogdown::new_post()` command in R to start a new post. Check out the help file for options to add.

This will create a new subdirectory in the `content/post` directory. This subdirectory can contain files needed for the post, like images. The post itself will be found in `index.rmd` of this subdirectory. This is a regular R Markdown file and you can do all of the usual stuff here, like:

```{r}
library(ggplot2)
ggplot(mpg, aes(displ, hwy, colour = class)) + 
  geom_point()+
  theme_bw()
```

## Serving the Site

To get a preview of what the site will look like, you can:

1. Use the Addin menu to go to `BLOGDOWN > Serve Site`.
2. Use the R command `blogdown::serve_site()`.

Either way, for this to work, your working directory must be the top-level directory of the site. 

This command will serve up a version of the site on a local port of your computer (reported to you) and should display it directly in RStudio. This server will remain up and listen for changes. It should update any time you save a file.

## Buiding the Site

When you are ready to share your site with the world, you need to build it. To build your site, just run the following R command:

```r
blogdown::build_site()
```

This command will create a `public` directory that contains your entire site. You can copy all of the files here to a public server and they should display correctly.

## Changing Site Design

If you want to mess about with the overall site design, you will want to learn a little more about how [Hugo](https://gohugo.io/) works. Many of the useful parameters (including the theme) can be adjusted in the top-level `config.yaml` file. Generally, you should only be modifying that file and files in the content directory, unless you are messing about with theming.

